#!/bin/bash

echo  _    _                                 _       _            
echo | |  | |                               | |     | |           
echo | |__| | __ _ ___ ___   _   _ _ __   __| | __ _| |_ ___ _ __ 
echo |  __  |/ _` / __/ __| | | | | '_ \ / _` |/ _` | __/ _ \ '__|
echo | |  | | (_| \__ \__ \ | |_| | |_) | (_| | (_| | ||  __/ |   
echo |_|  |_|\__,_|___/___/  \__,_| .__/ \__,_|\__,_|\__\___|_|   
echo                              | |                             
echo                              |_|                             

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ7~:..!JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ7~:  .^7~..!JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ?!7?^  .7JYYYYJ!..~JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ?!:. .      :!JYYYYYJ!. ^?YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ~:. .^!?JJ?7!~^:.:?YYYYYYY7: ^?YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ   ~JYYYYYYYYYYYYJJYYYYYYYYY7: :7YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ.   .~JYYYYYYYYJ?JJYYYYYYYYYYY?^ :7YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ.     .~JYYYYYYJ~..:^~!7?JYYYYYY?^ .!JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ.        ^?YYYYYY?^       ^?YYYYYYJ~..!JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ.          ^?YYYYYYJ~.      :7YYYYJ7^  :JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ7~:.        :7YYYYYYJ!.      :!^.  :~7?YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ7~^.      :7YYYYYYY!.  :~:.:~7JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ?!^.    :!JYJ7~:  .!YYJYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ?!~:  .:  .^!?JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ7~~7JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYY?!JYYYYY?~~~~~~~7YYYJ7~^::::^!?YYYY!~~~~~~~~!7JYYY!~~~~~~~~~!?JYYYJ~~~~~~~~JYYYJ7~^:::^~7JYYYYYYYYYYYYY?!^^::^^!YYYYYYYYYYY7.!YYYYYYYY!~?YYYYYYYYYYY?~??~~~~~~~~~~~~!YYYYYYYYYJ!~~~~~~~JYYYYYYYYYYYY!:?YYYYYYYY!~~~~~~~~~!?YYYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYY7  ^7JYY7       ~YJ~.          :7YY:          .~JY.           .~JYJ        ?YJ~.         ^JYYYYYYYYYY7:        7YYYYYYYYYY!   ~YYYYYYY~  :!JYYYYY?~:  7!            :YYYYYYYYYJ.      .JYYYYYYYYYYJ^  .7YYYYYYY:           ^JYYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYY7    .^?!       ~J:              !Y:            :J:             .?J.       ??.         ^7YYYYYYYYYYY~        .?YYYYYYYYYJ^     ^JYYYYY~    .^7?!:     77         ...~YYYYYYYYYJ.      .JYYYYYYYYY?:     ~YYYYYY:            ^YYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYY7       .       !!                J:             ?:              :J.       ?^       .^?YYYYYYYYYYYY?        :JYYYYYYYYYJ:       .?YYYY~               77         .::~YYYYYYYYYJ.      .JYYYYYYYY7.       ^JYYYY:            ?YYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYY7               !~                ?:            :J:              .J.       ?:       .7YYYYYYYYYYYYY7        .::::::.?Y7.          !YYY~               77          . ^YYYYYYYYYJ.       .::.7YYY!          .?YYY:            ^JYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYY7               !?.              ^Y:           ~JY:              !J.       ?7         .!JYYYYYYYYYYJ:              :J!             ~YY~               77         .::~YYYYYYYYYJ.           7YJ^             7YY:             ?YYYYYYYYYYYYYY
echo YYYYYYYYYYYYYY7               ~Y?:           .~YY:           ~YY.            :7YJ.       ?Y7:         .!JYYYYYYYYYJ~            ~J^               :J!               77            :YYYYYYYYYJ.           7?:               ~Y:            ^JYYYYYYYYYYYYYY
echo YYYYYYYYYYYYYY?.:::::::::::::.!YYY?~:..  ..^!JYYY^............!Y^.......::^~?YYYJ:.::::::?YYJ7~:.....:~7YYYYYYYYYYYYJ!^......^!JY~.:::::::::::::::.^~.:::::::::::::.?7.::::::::::.~YYYYYYYYYJ:.:::::::::.!:.::::::::::::::..~^.::::::::^!?YYYYYYYYYYYYYYYY
